#lang sicp
(define (square x)
  (* x x))
(define (abs x)
  (cond ((< x 0) (- x))
	 (else x)))
(define (improve guess x)
  (/ (+ (/ x (square guess)) 
	(* 2 guess))
     3))
(define (good-enough? previous-guess guess)
  (< (abs (/ (- guess previous-guess) guess)) 0.00000000001))
(define (cubrt-iter guess x)
  (if (good-enough? (improve guess x) guess)
    guess
    (cubrt-iter (improve guess x) x)))
(define (cubrt x)
  (cubrt-iter 1.0 x))
